require 'open3'
require 'rubygems'
require 'bagit'
require 'exifr'
require 'find'
require 'json'
require 'kdl'
require 'lorax'
require 'mustache'
require 'nokogiri'
require 'pathname'
require 'rails'

require 'tempfile'

require 'kdl/access_package'
require 'kdl/aip_maker'
require 'kdl/dip_maker'
require 'kdl/mets'
require 'kdl/mets_fixer'
require 'kdl/page'
require 'kdl/solr_maker'
require 'kdl/tiler'
